server:
  port: 8080

spring:
  profiles:
    active: dev
  config:
    use-legacy-processing: true
  application:
    name: membership-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

token:
  expiration-time : 3600000
  secret-key: ENC(zehmic1AsPolW19uG2XQ7Jgaa0Z1kUHZ)
  logout-token-expiration-time : 3600

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

oauth:
  kakao:
    rest-api-key : ENC(nJ2zapDuZl2hWWwOL0X/7Z9NGRIbi2ja+LGQeD7rjkqmenvKIBdeoUMtw4bAjOOS)
    redirect-url : ENC(EA4SxFO3/bGW5FHQMSXflASYduRA5wfVlaG1eu4nAz27VXNoGgup1Q7rOawlUrXF)
    auth-url : https://kauth.kakao.com
    password : ENC(rv8Qph3VurYZgBfvLo33SUPPosUgUzub)
  naver:
    rest-api-key: ENC(JaSzrQp22mx+MhdhXpCVF6LRkp/bm2luSNiJT2FYI/Q=)
    redirect-url: ENC(EgR5oDGO3zCRwzgEMcd2lpForBO5A2nZRU3+THGx5KKMljqlpemtTbctn1ADlQiJ)
    auth-url: https://nid.naver.com
    password: ENC(5TCiLaS4uEaaBh1nxgfZ+SDCffAAHhbr)
    client-secret: ENC(ANII7TSnW/iVYEel6Q2QFzPhKx2zXqY4)

eureka:
  instance:
    hostname: localhost                   #윈도우 경우 필요
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://database-kyuseok.cp43k9flv4ax.ap-northeast-2.rds.amazonaws.com/membership?useUnicode=true&characterEncoding=utf8
    username: ENC(E6qfrqxgTgnbL+fb4JfPEg==)
    password: ENC(+mBsJs8hgJL3omVzvToImV300v7YL+S0)
