server:
  port: 8080

spring:
  application:
    name: membership-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
token:
  expiration-time : 3600000
  secret-key: secretKey

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

oauth:
  kakao:
    rest-api-key : ENC(nJ2zapDuZl2hWWwOL0X/7Z9NGRIbi2ja+LGQeD7rjkqmenvKIBdeoUMtw4bAjOOS)
    redirect-url : ENC(EA4SxFO3/bGW5FHQMSXflASYduRA5wfVlaG1eu4nAz27VXNoGgup1Q7rOawlUrXF)
    kakao-auth-url : https://kauth.kakao.com
    password : ENC(rv8Qph3VurYZgBfvLo33SUPPosUgUzub)
